name: Generate Pacman SVG

on:
  schedule:
    - cron: "0 0 * * *"   # هر روز نیمه‌شب UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run snk to build pacman
        uses: Platane/snk@v3
        with:
          github_user_name: sinaha81

      - name: Upload pacman.svg
        run: |
          mkdir -p output
          mv dist/pacman.svg output/pacman.svg

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/pacman.svg
          git commit -m "Update pacman SVG"
          git push
