name: Generate Pacman (Dark & Light)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sinaha81
          snake_type: pacman
          outputs: |
            dist/pacman-light.svg
            dist/pacman-dark.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
